// <auto-generated />
namespace Runniac.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class CourseFileName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CourseFileName));
        
        string IMigrationMetadata.Id
        {
            get { return "201503262215185_CourseFileName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
